/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f670a938-7ce6-4ddb-9c9a-042bb328a210",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_kgdlkEEyc",
    "aws_user_pools_web_client_id": "7p4chgap7jg2de8972q1vpvgd3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3iehr3cwejgcnp2mtihpxa675u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mmnuk5hqcrg4ho3btrqnfes6w4"
};


export default awsmobile;
